"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { useAuth } from "@/contexts/AuthContext";

// ===========================================
// Types
// ===========================================

interface Message {
  id: string;
  author_type: "customer" | "agent" | "system";
  author_email: string;
  body: string;
  is_public: boolean;
  created_at: string;
}

interface DraftSource {
  type: "kb" | "ticket";
  id: string;
  title: string;
  similarity: number;
}

interface Draft {
  id: string | null;
  content: string;
  confidenceScore: number;
  confidenceLevel: "high" | "medium" | "low";
  sources: DraftSource[];
  isFallback?: boolean;
  fallbackReason?: string;
}

interface Ticket {
  id: string;
  zendesk_id: string;
  subject: string;
  status: string;
  priority: string | null;
  requester_email: string;
  tags: string[];
  created_at: string;
  updated_at: string;
  messages: Message[];
  drafts: Draft[];
}

// ===========================================
// Component
// ===========================================

export default function TicketDetailPage() {
  const params = useParams();
  const ticketId = params.id as string;
  const { profile } = useAuth();

  const [ticket, setTicket] = useState<Ticket | null>(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);
  const [sending, setSending] = useState(false);
  const [draftContent, setDraftContent] = useState("");
  const [draftMeta, setDraftMeta] = useState<Omit<Draft, "content"> | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [successMessage, setSuccessMessage] = useState<string | null>(null);

  const hasAutoGenerated = useRef(false);
  const organizationId = profile?.organizationId;
  const userId = profile?.id;

  const getConfidenceLevel = (score: number): "high" | "medium" | "low" => {
    if (score >= 0.7) return "high";
    if (score >= 0.4) return "medium";
    return "low";
  };

  const fetchTicket = useCallback(async () => {
    try {
      const response = await fetch(`/api/tickets/${ticketId}`);
      if (response.ok) {
        const data = await response.json();
        setTicket(data.ticket);
        // Set existing draft if exists
        if (data.ticket.drafts && data.ticket.drafts.length > 0) {
          const latestDraft = data.ticket.drafts[0];
          setDraftContent(latestDraft.content);
          setDraftMeta({
            id: latestDraft.id,
            confidenceScore: latestDraft.confidence_score,
            confidenceLevel: getConfidenceLevel(latestDraft.confidence_score),
            sources: latestDraft.sources || [],
            isFallback: latestDraft.is_fallback,
            fallbackReason: latestDraft.fallback_reason,
          });
          hasAutoGenerated.current = true;
        }
        return data.ticket;
      } else {
        setError("Failed to load ticket");
        return null;
      }
    } catch (err) {
      setError("Failed to load ticket");
      console.error(err);
      return null;
    } finally {
      setLoading(false);
    }
  }, [ticketId]);

  const generateDraft = useCallback(async () => {
    if (!organizationId || !userId) return;

    setGenerating(true);
    setError(null);

    try {
      const response = await fetch("/api/drafts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          ticketId,
          organizationId,
          userId,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to generate draft");
      }

      setDraftContent(data.draft.content);
      setDraftMeta({
        id: data.draft.id,
        confidenceScore: data.draft.confidenceScore,
        confidenceLevel: data.draft.confidenceLevel,
        sources: data.draft.sources || [],
        isFallback: data.draft.isFallback,
        fallbackReason: data.draft.fallbackReason,
      });
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to generate draft");
    } finally {
      setGenerating(false);
    }
  }, [ticketId, organizationId, userId]);

  // Initial fetch
  useEffect(() => {
    if (ticketId) {
      fetchTicket();
    }
  }, [ticketId, fetchTicket]);

  // Auto-generate draft after ticket loads (if no existing draft)
  useEffect(() => {
    if (
      ticket &&
      !hasAutoGenerated.current &&
      !generating &&
      organizationId &&
      userId &&
      !draftContent
    ) {
      hasAutoGenerated.current = true;
      generateDraft();
    }
  }, [ticket, generating, organizationId, userId, draftContent, generateDraft]);

  const handleSend = async () => {
    if (!draftContent.trim() || !organizationId) return;

    setSending(true);
    setError(null);
    setSuccessMessage(null);

    try {
      const response = await fetch(`/api/tickets/${ticketId}/reply`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          content: draftContent,
          draftId: draftMeta?.id,
          organizationId,
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to send reply");
      }

      setSuccessMessage("Reply sent successfully!");
      setDraftContent("");
      setDraftMeta(null);
      hasAutoGenerated.current = true; // Don't auto-generate again

      // Refresh ticket to show new message
      await fetchTicket();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to send reply");
    } finally {
      setSending(false);
    }
  };

  const getConfidenceColor = (level: string) => {
    switch (level) {
      case "high":
        return "bg-green-100 text-green-800";
      case "medium":
        return "bg-yellow-100 text-yellow-800";
      case "low":
        return "bg-red-100 text-red-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case "new":
        return "bg-blue-100 text-blue-800";
      case "open":
        return "bg-yellow-100 text-yellow-800";
      case "pending":
        return "bg-orange-100 text-orange-800";
      case "solved":
        return "bg-green-100 text-green-800";
      default:
        return "bg-gray-100 text-gray-800";
    }
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString("en-US", {
      month: "short",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  if (loading) {
    return (
      <div className="p-8 max-w-4xl mx-auto">
        <div className="animate-pulse">
          <div className="h-4 bg-gray-200 rounded w-24 mb-8"></div>
          <div className="bg-white rounded-lg border p-6 h-96"></div>
        </div>
      </div>
    );
  }

  if (!ticket) {
    return (
      <div className="p-8">
        <div className="text-center text-gray-500">
          <p>Ticket not found</p>
          <Link href="/tickets" className="text-blue-600 hover:underline mt-2 block">
            Back to tickets
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-4xl mx-auto">
      <div className="mb-6">
        <Link href="/tickets" className="text-sm text-gray-600 hover:text-black">
          ← Back to tickets
        </Link>
      </div>

      {error && (
        <div className="mb-4 p-3 bg-red-50 text-red-700 rounded-lg text-sm">
          {error}
        </div>
      )}

      {successMessage && (
        <div className="mb-4 p-3 bg-green-50 text-green-700 rounded-lg text-sm">
          {successMessage}
        </div>
      )}

      {/* Single Card */}
      <div className="bg-white rounded-lg border">
        {/* Header */}
        <div className="p-6 border-b">
          <div className="flex items-start justify-between">
            <div>
              <h1 className="text-xl font-bold mb-2">{ticket.subject}</h1>
              <div className="flex items-center gap-3 text-sm text-gray-600">
                <span>#{ticket.zendesk_id}</span>
                <span>•</span>
                <span>{ticket.requester_email}</span>
              </div>
            </div>
            <div className="flex gap-2">
              <span className={`px-2 py-1 text-xs font-medium rounded-full ${getStatusColor(ticket.status)}`}>
                {ticket.status}
              </span>
              {ticket.priority && (
                <span className="px-2 py-1 text-xs font-medium rounded-full bg-gray-100 text-gray-800">
                  {ticket.priority}
                </span>
              )}
            </div>
          </div>
        </div>

        {/* Messages */}
        <div className="p-6 space-y-4 max-h-[400px] overflow-y-auto border-b">
          {ticket.messages.length === 0 ? (
            <p className="text-gray-500 text-center py-8">No messages yet</p>
          ) : (
            ticket.messages.map((message) => (
              <div
                key={message.id}
                className={`p-4 rounded-lg ${
                  message.author_type === "customer"
                    ? "bg-blue-50 mr-12"
                    : message.author_type === "agent"
                    ? "bg-green-50 ml-12"
                    : "bg-gray-50 mx-6"
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm font-medium">
                    {message.author_type === "customer"
                      ? "Customer"
                      : message.author_type === "agent"
                      ? "Agent"
                      : "System"}
                  </span>
                  <span className="text-xs text-gray-500">
                    {formatDate(message.created_at)}
                  </span>
                </div>
                <p className="text-sm text-gray-700 whitespace-pre-wrap">
                  {message.body}
                </p>
              </div>
            ))
          )}
        </div>

        {/* Draft Reply Section */}
        <div className="p-6">
          <div className="flex items-center justify-between mb-3">
            <span className="text-sm font-medium text-gray-700">Your Reply</span>
            <div className="flex items-center gap-2">
              {draftMeta && (
                <span
                  className={`px-2 py-1 text-xs font-medium rounded-full ${getConfidenceColor(
                    draftMeta.confidenceLevel
                  )}`}
                >
                  AI: {(draftMeta.confidenceScore * 100).toFixed(0)}% confidence
                </span>
              )}
              {draftMeta?.isFallback && (
                <span className="px-2 py-1 text-xs font-medium rounded-full bg-yellow-100 text-yellow-800">
                  Needs review
                </span>
              )}
            </div>
          </div>

          {generating ? (
            <div className="border rounded-lg p-4 min-h-[150px] flex items-center justify-center bg-gray-50">
              <div className="text-center">
                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-black mx-auto mb-2"></div>
                <p className="text-sm text-gray-500">Generating response...</p>
              </div>
            </div>
          ) : (
            <textarea
              value={draftContent}
              onChange={(e) => setDraftContent(e.target.value)}
              placeholder="Type your reply..."
              className="w-full border rounded-lg p-4 min-h-[150px] text-sm resize-none focus:ring-2 focus:ring-black focus:border-transparent"
            />
          )}

          {/* Sources */}
          {draftMeta?.sources && draftMeta.sources.length > 0 && (
            <div className="mt-3 flex flex-wrap gap-2">
              <span className="text-xs text-gray-500">Sources:</span>
              {draftMeta.sources.slice(0, 3).map((source, i) => (
                <span
                  key={i}
                  className="text-xs bg-gray-100 rounded px-2 py-1"
                  title={source.title}
                >
                  {source.type === "kb" ? "📄" : "🎫"} {source.title.slice(0, 30)}
                  {source.title.length > 30 ? "..." : ""}
                </span>
              ))}
            </div>
          )}

          {/* Action Buttons */}
          <div className="flex gap-2 mt-4">
            <button
              onClick={generateDraft}
              disabled={generating}
              className="px-4 py-2 border border-gray-300 rounded-lg hover:bg-gray-50 transition text-sm disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {generating ? "Generating..." : "Regenerate"}
            </button>
            <button
              onClick={handleSend}
              disabled={sending || !draftContent.trim()}
              className="flex-1 py-2 bg-black text-white rounded-lg hover:bg-gray-800 transition text-sm disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {sending ? "Sending..." : "Send Reply"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
